### ISSUE TITLE
[PROJECT/BUILD] Missing files in repo

### ISSUE THREAD

**Issue by fromanan** [HaydenD100/3dEngine2.0#2]
Not sure how relevant it is, but the 'Engine/Debug' folder does not seem to be included in the GitHub repo on the main branch, but was referenced in the solution file and listed as missing.

![Screenshot 2024-07-30 164644](https://github.com/user-attachments/assets/15e589ed-69c2-4d06-afdd-ab886bd26443)

**Comment by HaydenD100** [comment]
Hi, that is something, I included to draw the collision boxes for bullet physics but never ended up finishing and isn't used in the main engine.
